### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by larrynikx** [deveth0/httpclient-spring-boot-starter#17]
Facing this error on attempt to add the dependency:

Cannot resolve de.dev-eth0.spring-boot.httpclient:httpclient-spring-boot-starter:unknown

Am I missing a repository? I have tried your sonatype repository but I get a 401 unauthorized.

**Environment**
SpringBoot: 2.3.1
SpringCloud: Hoxton.SR6

**Comment by deveth0** [comment]
hey, I think you are missing the version number, please add it to your pom (current release is 1.1.0):

https://repo1.maven.org/maven2/de/dev-eth0/spring-boot/httpclient/httpclient-spring-boot-starter/1.1.0/

**Comment by larrynikx** [comment]
Thanks! all good now..maybe you can update the readme with the version?

**Comment by deveth0** [comment]
Good to hear! Enjoy the starter! I added a short notice, problem is I don't want ot update the README after a release ;)
